# Generated by Django 5.2 on 2025-08-25 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Quetta', 'Quetta'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Karachi', 'Karachi'), ('Peshawar', 'Peshawar')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.citymodel')),
            ],
        ),
    ]
