# Generated by Django 5.2 on 2025-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='city',
            field=models.CharField(choices=[('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Quetta', 'Quetta'), ('Islamabad', 'Islamabad'), ('Peshawar', 'Peshawar')], max_length=50),
        ),
    ]
